/// TEMPLATE FILE - COPY TO dev_credentials.dart AND FILL IN YOUR CREDENTIALS
/// DO NOT EDIT THIS FILE WITH ACTUAL CREDENTIALS
library;

class DevCredentials {
  static const Map<String, Map<String, String>> credentials = {
    'Classic': {
      'url': 'your.classic.server.url',
      'username': 'your_username',
      'password': 'your_password',
    },
    'Angora': {
      'url': 'your.angora.server.url',
      'username': 'your_username',
      'password': 'your_password',
    },
  };
}
